added a plugin to dump test classpath and their timestamp. I'm using this to diagnose NoClassDefFoundError during unit tests, which I suspect is caused by the local maven repository alteration during the test